### ISSUE TITLE
Have preview fill fragment

### ISSUE THREAD

**Issue by alecgorge** [iamMehedi/MVBarcodeReader#1]
Right now, if you embed the scanner in the fragment the preview does not take up the whole screen and there is some black area on the right hand side.

It seems to be resized to fit with the proper aspect ratio. Is there an option to have it fill all available space even if it means cropping it a bit?

Thanks for such a useful library! It works great!

**Comment by iamMehedi** [comment]
@alecgorge currently there is no such option to force the preview size to fill available space. The preview size is resized to match the aspect ratio of the chosen camera resolution and it tries to fill available space if that's possible without breaking the aspect ratio. I'll see what I can do to add such an option.

**Comment by iamMehedi** [comment]
@alecgorge This should be resolved in the latest version of the library (1.0.0).

**Comment by alecgorge** [comment]
Thank you! This works great!
