### ISSUE TITLE
Barcode Scan is not working on Nexus 6P with Android 7.0

### ISSUE THREAD

**Issue by kahmed2014** [iamMehedi/MVBarcodeReader#11]
Hello Mehedi,

Barcode scan is not working on nexus 6p with Android 7.0.
It is showing camera view and keep in camera view not able to detect the  barcode. 

Please fix this issue.

**Comment by iamMehedi** [comment]
Does the same barcode gets detected on other devices or OS versions?

**Comment by kahmed2014** [comment]
Yes, It is working fine.

**Comment by iamMehedi** [comment]
please provide the barcode image you're trying to scan along with the version of the play services you have on the device.

**Comment by iamMehedi** [comment]
closing due to no response.
