### ISSUE TITLE
Freeze bug

### ISSUE THREAD

**Issue by jemshit** [iamMehedi/MVBarcodeReader#13]
Hi. When "Don't keep activities" is checked in Settings->Developer Options, and i open Activity containing `BarcodeCaptureFragment`, i press Home button, then open Activity again. I see camera is freezed

**Comment by iamMehedi** [comment]
The sample app works perfectly in the scenario you described. My guess is it has something to do with the fragment not being recreated and added when the activity is coming back.

**Comment by jemshit** [comment]
Added fragment in `onCreate` of Activity

**Comment by iamMehedi** [comment]
Cannot reproduce. If you are still facing this issue on multiple devices then please then provide a sample code to reproduce the issue along with details of the device.
