### ISSUE TITLE
Gradle link is unresolved

### ISSUE THREAD

**Issue by SamuelYvon** [iamMehedi/MVBarcodeReader#17]
When setting up in android studio, it cannot find the latest version of the project

![image](https://cloud.githubusercontent.com/assets/12652003/26651650/60743042-461b-11e7-9b31-1efe4337391d.png)

**Comment by iamMehedi** [comment]
`LATEST_VERSION` needs to be replaced with the actual version number i.e `1.0.9`

**Comment by SamuelYvon** [comment]
I thought it was some sort of magic link for the latest version, derp derp!

Thanks!
