### ISSUE TITLE
Support library version

### ISSUE THREAD

**Issue by Wojtek1234** [iamMehedi/MVBarcodeReader#3]
Hi, can you please provide version without depedencies for support library ?

setting transitive to false do not solve problems :)

cheers and thanks for library, it is very usefull :)

Wojtek

**Comment by iamMehedi** [comment]
@Wojtek1234 can you please describe a little about the problem you are facing.

**Comment by Wojtek1234** [comment]
I would like to decide which of support library version add. At this point your library force me to use 25.0.1


cheers

**Comment by iamMehedi** [comment]
@Wojtek1234 v1.0.3 might solve your issue. If not then you can always fork the repo and use dependencies as per your requirement.

**Comment by Wojtek1234** [comment]
yes I can :)

many thanks !

cheers!
