### ISSUE TITLE
Camera aspect is not as default one.its obnormal

### ISSUE THREAD

**Issue by rajkumaranbu94** [iamMehedi/MVBarcodeReader#7]
In android version 6.0,Permission requires to open the camera,after accept the permission,camera screen open with obnormal aspect ratio.This is happen only after accepting the permission for open camera.i am using activity,intent to camera screen.
Sample code used to access camera:-
new MVBarcodeScanner.Builder()
                    .setScanningMode(MVBarcodescanner.)
                    .setFormats(mFormats)
                    .build()
                    .launchScanner(this, REQ_CODE);
**Normal Camera Scan**
![normal](https://cloud.githubusercontent.com/assets/14178027/23207660/11305b14-f918-11e6-8e88-cb408438f4d7.jpg)
**Obnormal Camera Scan**
![obnormal](https://cloud.githubusercontent.com/assets/14178027/23207686/26e7b966-f918-11e6-895a-5cde08dde05c.png)

**Comment by rajkumaranbu94** [comment]
Camera is looking like by using some lens to see the pictures.

**Comment by iamMehedi** [comment]
Cannot reproduce it. Which device are you on? Are you using the latest version of the library?

**Comment by rajkumaranbu94** [comment]
@iamMehedi Yes i m using latest version 1.0.7,and device which i was using to test MotoG(android 6),Mi (android 6),Lenovo k3(android 6).i just think that it only happen in android version 6.

**Comment by rajkumaranbu94** [comment]
And more thing,its only happen after accepting the permission,dialog rise to ask to access your camera before that one snackbar also display with permission message and 'Ok' button.After that i close the camera and try to reopen,its work well.Issue occurs for me when accept permission to access camera that's it.
Go throught it and try to help me.

**Comment by iamMehedi** [comment]
I am yet to reproduce it. But for the time being if the camera permission dialog is causing this issue, you can just handle the permission yourself i.e 
- ask for camera permission if you don't have it already
- launch the scanner after getting the permission

**Comment by rajkumaranbu94** [comment]
By default your library manifest had that permission to open device camera.Even i include permission in my project manifest file.it doesn't works.And also write code before launch the scanner,it won't work.
Suggest me some solution i ll try with that we will resolve that issue soon.

**Comment by iamMehedi** [comment]
try out the latest commit fb81b08 and let me know if it still has the same issue.

**Comment by rajkumaranbu94** [comment]
@iamMehedi Issues cleared in one way of approach i.e when i install fresh application,permission dialog appear and accept it,camera opens normally(Snackbar permission not avail in that situation).If i minimize or close the application and change the camera permission in settings(apps-->permissions-->Camera-->unselect permission) and again back to the application and try to access camera its remains same issue(in that situation snackbar appears) i.e In this time both snackbar permission and default permission asking to access camera.Actually the problem arises after snackbar appears screen.

Snackbar ScreenShot
![snackbarpermission](https://cloud.githubusercontent.com/assets/14178027/23330153/e1f4e9e4-fb6c-11e6-9412-e2a968548697.png)

**Comment by iamMehedi** [comment]
@rajkumaranbu94 try out the new version `1.0.8`, this should be fixed.

**Comment by rajkumaranbu94** [comment]
@iamMehedi its work,thank you.
